DCT.Monitor.Server/Controllers/SiteManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DCT.Monitor.Server.Helpers;
using DCT.Monitor.Server.Models;
using DCT.Monitor.Server.Security;
using DCT.Monitor.Entities;
using DCT.Monitor.Modules;
using DCT.Monitor.Modules.Implementation.PageModule;
using DCT.Monitor.Modules.Implementation.ProviderModule;
using DCT.Monitor.Modules.Implementation.SiteManager;
using DCT.Monitor.Modules.Implementation.UserModule;

namespace DCT.Monitor.Server.Controllers
{
	[Authorize]
	public class SiteManagerController : BaseController
	{
		IUserModule userModule = new UserModule();
		IProviderModule providerModule = new ProviderModule();
		ISiteManagerModule siteModule = new SiteManagerModule();
        IPageModule pageModule = new PageModule();

		[ActionName("Content")]
		public ActionResult ContentAction(string view)
		{
			return View(view);
		}

		[ActionName("create")]
		public ActionResult CreateSite(string domain)
		{
            if (Session.User != null)
            {
                var site = new Site() { Domain = domain };
                return Redirect(Url.CreateSite());
            }
            else
            {
                return Redirect(Url.Logon());
            }
		}

        [ActionName("Sites"), HttpGet]
        public ActionResult Sites()
        {
            SiteListModel listOfSites = new SiteListModel();
            listOfSites.Sites = siteModule.GetSitesByUser(Session.User);
            listOfSites.Session = Session;
            ViewData.Model = listOfSites;

            return View("SitesNew");
        }

		[ActionName("Sites"), HttpPost]
		public ActionResult Sites(SiteListModel model)
		{
			if (ModelState.IsValid)
			{
				var site = new Site() {Domain = model.SiteModel.Domain, ContainsSubdomains = model.SiteModel.IgnoreSubdomains };
				siteModule.CreateSite(Session.User, site);
					
				model.SiteModel.Domain = string.Empty;
                
                return Redirect(Url.Sites());
			}

			return Sites();
		}

		public ActionResult DeleteSite(Guid siteId)
		{
			if (Session.User != null)
			{
				siteModule.Delete(siteId);
				return Redirect(Url.Sites());
			}
			else
			{
				return Redirect(Url.Logon());
			}
		}

		[HttpPost, Authorize]
		public ActionResult EditSite(SiteListModel model)
		{
			if (Session.User != null)
			{
				siteModule.EditDomain( new Site()
										{
											Id = model.SiteModel.Id, 
											UserId = Session.User.Id,
											Domain = model.SiteModel.Domain, 
											ContainsSubdomains = model.SiteModel.IgnoreSubdomains
										});
				return Redirect(Url.Sites());
			}
			else
			{
				return Redirect(Url.Logon());
			}
		}

        public ActionResult EditPages(Guid siteId)
        {
            List<Page> pages = pageModule.GetPagesBySiteId(siteId);

            return View(pages);
        }

        public ActionResult DeletePage(Guid pageId)
        {   
            var page = pageModule.GetPageById(pageId);
            pageModule.DeletePage(page);

            return Redirect(Url.Pages(page.DomainId)); 
        }
                
        [HttpPost]
        public ActionResult EditPage(Guid id)
        {
            var pagePattern = Request["Page_" + id];

            var page = pageModule.GetPageById(id);
            page.PagePattern = pagePattern;
            pageModule.UpdatePage(page);

            return Redirect(Url.Pages(page.DomainId));
        }
        

        [HttpPost]
        public ActionResult AddPage()
        {
            var pagePattern = Request["PageModel.Page"];
            var siteId = Guid.Parse(Request["siteId"]);

            var page = new Page() { DomainId = siteId, PagePattern = pagePattern };
            pageModule.CreatePage(page);

            return Redirect(Url.Pages(siteId));
        }

        [ActionName("Pages"), HttpGet]
        public ActionResult Pages(Guid siteId)
        {            
            var listOfSites = new PageListModel();
            listOfSites.Pages = pageModule.GetPagesBySiteId(siteId);
            listOfSites.Session = Session;
            listOfSites.Site = siteModule.GetSite(siteId);
            ViewData.Model = listOfSites;
            ViewData.Add("SiteId",siteId);

            return View();           
        }
	}
}

DCT.Monitor.Server/Views/Shared/EditUserControl.cshtml
@{
	Layout = null;  
}
@model DCT.Monitor.Server.Models.SiteListModel

@using (Html.BeginForm("EditSite", "SiteManager", FormMethod.Post))
{
	<div class="fieldBox">
		<label for="domain">Site's Domain:</label>
		<div class="border">
			@Html.TextBoxFor(m => m.SiteModel.Domain, new { Class = "edit" })
		</div>
		<div class="error">
			@Html.ValidationMessageFor(m => m.SiteModel.Domain)
		</div>
	</div>
	<br />
	//TODO: Traking
@*	<div class="fieldBox">
		<label for="domain">Track subdomains?</label>
		@Html.CheckBoxFor(m => m.SiteModel.IgnoreSubdomains)
	</div>*@
	<div class="fieldBox">
		<div class="error">
		<p class="validateTips"></p>
			@Html.ValidationMessageFor(m => m.SiteModel )
		</div>
	</div>
	@Html.HiddenFor(m => m.SiteModel.Id);
}

DCT.Monitor.Server/Views/Shared/FooterContent.cshtml
@using DCT.Monitor.Server.Helpers;

<div id="blocks">
	<ul>
		<li> <img src="@Url.Content("~/Content/img/img1.png")" alt="" title="" />
			@*<h2><a href="#" title="">One click Desktop access</a></h2>*@
			<p>One click <b>to download a desktop client</b> for Monator to always know about users’ activity on your site using Monator from your computer.</p>
			<p class="more"><a href="@*@Url.Downloads().AsUrl()*@/distributives/win/setup.exe" title="">Download</a></p>
		</li>
		<li> <img src="@Url.Content("~/Content/img/img3.png")" alt="" title="" />
			@*<h2><a href="#" title="">One click Desktop access</a></h2>*@
			<p>One click <b>to become a user of the web-client</b> of Monator to always know about users’ activity on your site using Monator from the Internet.</p>
			@*<p class="more"><a href="#" title="">Download</a></p>*@
			<p class="more"><br /></p>
		</li>
	</ul>
</div>





DCT.Monitor.Server/Views/Shared/HeaderContent.cshtml
 @using DCT.Monitor.Server.Helpers;
 @using DCT.Monitor.Server.Controllers;

 @if (Request.IsAuthenticated)
 { 
	<ul>
		<li>You are logined as @Model.Session.User.UserName</li>
		<li> | </li>
		<li>@Url.Logoff().AsLink("Exit", "signin")</li>

	</ul>
    
 }
 else
 {
	 using (Html.BeginForm("Autorisation", "Home", FormMethod.Post, new { @class = "form", name = "form" }))
	 {
		<ul>
@*			<li>
			<a class="noline" href="@Url.Logon("google").AsUrl()" title="Facebook">
				<img src="@Url.Content("~/Content/img/facebook_16.png")" alt="" />
			</a>
			</li>*@
			<li>
				<a class="noline" href="@Url.Logon("twitter").AsUrl()" title="Twitter">
					<img src="@Url.Content("~/Content/img/twitter_16.png")" alt="" />
				</a>
			</li>
			<li>
				<a class="noline" href="@Url.Logon("google").AsUrl()" title="Google">
					<img src="@Url.Content("~/Content/img/google_16.png")" alt="" />
				</a>
			</li>
			<li>
				<a class="noline" href="@Url.Logon("linkedin").AsUrl()" title="LinkedIn">
					<img src="@Url.Content("~/Content/img/linkedin_16.png")" alt="" />
				</a>
			</li>
			<li>
				<a class="noline" href="@Url.Logon("myspace").AsUrl()" title="MySpace">
					<img src="@Url.Content("~/Content/img/myspace_16.png")" alt="" />
				</a>
			</li>
			<li>
				<a class="noline" href="@Url.Logon("vkontakte").AsUrl()" title="Vkontakte">
					<img src="@Url.Content("~/Content/img/vkontakte_16.png")" alt="" />
				</a>
			</li>
			<li class="text"><a href="@Url.Logon().AsUrl()" title="">Sign in</a> </li>
			<li> | </li>
			<li class="text"><a href="@Url.Register().AsUrl()" title="">Sign up</a></li>
		</ul>
	 }
 }
<script type="text/javascript">
	function PostAuth(path) {
		document.forms["form"].action = "/Account/Logon?site=" + path;
		document.forms["form"].method = "post";
		document.forms["form"].submit();
	}
</script>
@*<script type="text/javascript">
	function RedirToReg(path) {
		document.forms["form"].action = "/Account/Logon?site=" + path;
		document.forms["form"].method = "post";
		//ViewBag.Path = "?site=" + path;
		document.forms["form"].submit();
	}
</script>*@

DCT.Monitor.Server/Views/Shared/LogOnUserControl.cshtml
@model DCT.Monitor.Server.Models.AccountModel
@using DCT.Monitor.Server.Helpers

@using (Html.BeginForm("Logon", "Account", FormMethod.Post, new { @class = "form", name = "form" }))
{
    <fieldset class="signin">
		<div class="field">
			<div class="error">
				@Html.ValidationMessageFor( m => m.LogonModel)
			</div>
		</div>
        <div class="field">
            <label>
                Enter your User Name
            </label>
            <div class="border">
                @Html.TextBoxFor(m => m.LogonModel.UserName, new { Class = "short" })
            </div>
			<div class="error">
				@Html.ValidationMessageFor( m => m.LogonModel.UserName)
			</div>
        </div>
        <div class="field">
            <label>
                Enter your Password </label>
            <div class="border">
                @Html.PasswordFor(m => m.LogonModel.Password, new { Class = "short" })
            </div>
			<div class="error">
				@Html.ValidationMessageFor( m => m.LogonModel.Password)
			</div>
        </div>
        @Html.Hidden("ProviderId")
        @Html.Hidden("ProviderUserId")
        <div class="info">
            <label for="termsaccept">
				@Url.RetrivePassword().AsLink("Forgot your password?")
            </label>
        </div>
        <div class="buttons">
            <input type="button" class="button grey back" value="Back" />
            <input type="submit" class="button orange" value="Sign in" id="buttonsignin" />
        </div>
    </fieldset>
}

DCT.Monitor.Server/Views/Shared/RegisterUserControl.cshtml
@model DCT.Monitor.Server.Models.AccountModel
@using DCT.Monitor.Server.Helpers


@{
    var providerId = Convert.ToInt32(ViewData["ProviderId"]);
    if (providerId != 1 && providerId != null)
    {
@* <div>The binding will be added to your profile automatically!</div>*@
    }
}

@using (Html.BeginForm("Register", "Account", FormMethod.Post/*, new { @class = "form", name = "form" }*/))
{
    <fieldset class="signup">
        <div class="field">
            <label>
                User Name </label>
            <div class="border">
                @Html.TextBoxFor(m => m.RegisterModel.UserName, new { Class = "short" })
                
            </div>
			<div class="error">
				@Html.ValidationMessageFor(m => m.RegisterModel.UserName)<br />
			</div>
        </div>
        <div class="field">
            <label>
                Email </label>
            <div class="border">
                @Html.TextBoxFor(m => m.RegisterModel.Email, new { Class = "short" })
            </div>
			<div class="error">
				@Html.ValidationMessageFor(m => m.RegisterModel.Email)<br />
			</div>
        </div>
        <div class="field">
            <label>
                Password </label>
            <div class="border">
                @Html.PasswordFor(m => m.RegisterModel.Password, new { Class = "short" })
            </div>
			<div class="error">
				@Html.ValidationMessageFor(m => m.RegisterModel.Password)<br />
			</div>
        </div>
        <div class="field">
            <label>
                Confirm password</label>
            <div class="border">
                @Html.PasswordFor(m => m.RegisterModel.ConfirmPassword, new { Class = "short" })
                
            </div>
			<div class="error">
				@Html.ValidationMessageFor(m => m.RegisterModel.ConfirmPassword)<br />
				
			</div>
        </div>

        @Html.Hidden("ProviderId")
        @Html.Hidden("ProviderUserId")
        @*<div class="info">
		<input type="checkbox" id="termsaccept" />
		<label for="termsaccept">I accept Monator's <a target="_blank" href="/terms">Terms of Service</a></label>
		</div>*@
		<div>@Html.ValidationMessageFor(m => m.RegisterModel)</div>
        <div class="buttons">
            <input type="button" class="button grey back" value="Back" />
            <input type="submit" class="button orange" value="Sign up" id="buttonsignup" />
        </div>
    </fieldset>
}

DCT.Monitor.Server/Views/Shared/SiteGridControl.cshtml
@using DCT.Monitor.Server.Helpers
@model DCT.Monitor.Server.Models.SiteListModel
@{
	ViewBag.Title = "MyHome";
}

<div id="form" class="singleSite">
<fieldset class="signin">
		@if (Model.Sites == null || Model.Sites.Count == 0)
		{
			<div>Your domain list is empty!</div>
		}
		else
		{
			<table>
				<tr>
					<th><label>Site's Domain:</label></th>
					<th><label>Script link</label></th>
					<th>Copy script link</th>
					<th><label>Delete domain</label></th>
				</tr>
			    @foreach (var site in Model.Sites)
				{
					var id = site.Id + "_input";
					<tr>
					
						<td class="text">@site.Domain</td>
						<td id="tdbox" class="scriptText + @site.Domain">
							<div class="fieldBox">
								<div class="border">
									@Html.TextBox(id, Url.StringScript(site.Id.ToString()), new {id, Class="script"} )
								</div>
							</div>
						</td>
						<td class="text"><button id="@(site.Id)" type="button" class="copy-dynamic">Copy</button></td>
						@*<td><a id="@(site.Id)" class="copy-dynamic" href="#">Copy script</a></td>*@															  
						<td class="text">@Url.DeleteSite(site).AsLinkButton("Delete", "delete", "blue button")</td>
					</tr>
				}
			</table>
		}    
</fieldset>
</div>

DCT.Monitor.Server/Views/Shared/_Layout.cshtml
@using DCT.Monitor.Server.Controllers
@using DCT.Monitor.Server.Helpers

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head runat="server">
	<title>Monator - Site Monitoring Service - @ViewBag.Title</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link href="/Content/Monator.ico" type="image/x-icon" rel="icon" />
	<link href="@Url.Content("~/Content/style_new.css")" type="text/css" rel="stylesheet" />
	<link href="@Url.Content("~/Content/themes/ui-lightness/jquery-ui-1.7.2.custom.css")" type="text/css" rel="stylesheet" />
	<script src="/Scripts/jquery-1.5.1.min.js" type="text/javascript" language="javascript" ></script>	
	<script src="/Scripts/jquery-ui-1.8.13.custom.min.js" type="text/javascript"></script>
	<script src="/Scripts/myajax.js" type="text/javascript"></script>
	<script src="/Scripts/Cookies.js" type="text/javascript"></script>

	<script src="/Scripts/jquery.zclip.js" type="text/javascript"></script>
	@if (!Request.Url.Host.Contains("all"))
 {
	<script type="text/javascript">

			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-15461238-1']);
			_gaq.push(['_trackPageview']);

			(function () {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' :
	'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0];
				s.parentNode.insertBefore(ga, s);
			})();

	</script>
 }
	<script type="text/javascript">
		(function () {
			var m = document.createElement('script'); m.type = 'text/javascript'; m.async = true;
			m.src = 'http://@(Request.Url.Host)/service?siteid=@(BaseController.SelfSiteId)';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(m, s);
		})();
	</script>

@*	<script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php" type="text/javascript"></script>
	<script type="text/javascript">
		FB.init("@Skyner.Server.Extensions.Constants.FacebookApplicationKey", "Facebook"); 
	</script>*@
</head>
<body>
@{
	string menuItem = ViewBag.CurrentMenuItem;
	if (string.IsNullOrEmpty(menuItem)){ 
		menuItem = "home";
	}
}

<div id="wrapper">
	<div id="logo">
		<a title="Skyner Systems" href="@Url.Home().AsUrl()">
			<img src="@Url.Content("~/Content/img/logo-beta.png")" alt="Logo" />
		</a>
	</div>
	<div id="authorisation">
		@{Html.RenderPartial("HeaderContent");}
	</div>
	<div id="menu">
		<ul>
			<li>@Url.Home().AsLink("Home", menuItem == "home" ? "home current" : "home")</li>
			@if (Request.IsAuthenticated)
            {
                <li>@Url.MyHome().AsLink("My home", menuItem == "myhome" ? "myhome current" : "myhome")</li>
            }
            <li>@Url.Downloads().AsLink("Downloads", menuItem == "downloads" ? "downloads current" : "downloads")</li>
			<li>@Url.Faq().AsLink("FAQ", menuItem == "faq" ? "current faq" : "faq")</li>
			<li>@Url.ContactUs().AsLink("Contact us", menuItem == "contact" ? "contact current" : "contact")</li>
		</ul>
	</div>
	
		@RenderBody()

	@RenderSection("FooterSection", false)
	<div id="footer">
		<div class="menu">
			<ul>
			<li><a href="@Url.Home().AsUrl()" class="home current">Home</a> | </li>
			<li><a href="@Url.MyHome().AsUrl()" class="products">My home</a> | </li>
			<li><a href="@Url.Downloads().AsUrl()" class="company">Downloads</a> | </li>
			<li><a href="@Url.Faq().AsUrl()" class="support">FAQ</a> | </li>
			<li><a href="@Url.ContactUs().AsUrl()" class="contact">Contact us</a></li>
			</ul>
		</div>
		<p class="copyright">Copyright &copy; 2011 <a href="#"><img src="@Url.Content("~/Content/img/dct-logo.png")" alt="" /></a></p>
	</div>
</div>
<style type="text/css">
#footer {
	padding: 15px;
	border-top: 5px solid #64a6be;
	
	background: #ffffff;
	background: -webkit-gradient(linear, left top, left bottom, from(#ffffff), to(#eeeeee));
	background: -moz-linear-gradient(top, #ffffff, #eeeeee);
	filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff', endColorstr='#eeeeee');
	
	overflow: hidden;
}
#footer .menu {
}
#footer .menu ul {
	float: left;
}
#footer .menu ul li {
	color: #888;
	display: inline;
}
#footer .menu ul li a {
	color: #666;
}
#footer .copyright {
	float: right;
}
</style>

<style type="text/css">
#blocks {
}
#blocks ul {
	overflow: hidden;
	padding: 5px;
}
#blocks ul li {
	width: 465px;
	margin: 15px;
	padding: 10px 0;
	background: #fff;

	-moz-box-shadow: inset 0 0 5px #666;
	-webkit-box-shadow: inset 0 0 5px #666;
	box-shadow: inset 0 0 5px #666;

	float: left;
}

#blocks ul li h2 {
	padding: 5px 15px;
}
#blocks ul li h2 a {}
#blocks ul li p {
	padding: 0px 15px;
}
#blocks ul li p.more {
	padding: 0 15px;
	text-align: right;
}
#blocks ul li p.more a {
	color: #64a6be;
	text-decoration: underline;
	padding-right: 20px;		
}
  </style>
</body>
</html>

DCT.Monitor.Server/Views/Shared/_MyHomeLayout.cshtml
@using DCT.Monitor.Server.Controllers
@using DCT.Monitor.Server.Helpers
@{
	Layout = @"~/Views/Shared/_Layout.cshtml";
}

<div id="infoSite">
	<div class="verticalMenu">
		<ul>
			<li>@Url.Sites().AsLink("Viewing of your domains")</li>
			<li><br /></li>
			<li>@Url.ChangePassword().AsLink("Change password")</li>
			<li><br /></li>
			<li>@Url.AccountBinding().AsLink("Change your social binding")</li>
		</ul>
	</div>
		
	@RenderBody()
</div>

DCT.Monitor.Server/Views/Shared/_SimpleLayout.cshtml
@using DCT.Monitor.Server.Helpers

@{
    Layout = null;
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>@ViewBag.Title</title>
	<link href="@Url.Content("~/Content/style_new.css")" type="text/css" rel="stylesheet" />
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
</head>
<body>
    <div id="wrapper">
      <div id="logo"><a href="@Url.Home().AsUrl()"><img src="@Url.Content("~/Content/img/logo-beta.png")" alt=Logo"" /></a></div>

      @RenderBody()
    </div>

    @RenderSection("scripts")
</body>
</html>

DCT.Monitor.Server/Views/Shared/_SiteLayout.cshtml
@using Skyner.Server.Controllers
@using Skyner.Server.Helpers

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head runat="server">
	<title>Monator - Site Monitoring Service - @ViewBag.Title</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link href="/Content/Monator.ico" type="image/x-icon" rel="icon" />
	<link href="@Url.Content("~/Content/style_new.css")" type="text/css" rel="stylesheet" />
	<script src="/Scripts/jquery-1.4.4.js" type="text/javascript" language="javascript" ></script>	
	<script src="/Scripts/jquery-ui.js" type="text/javascript"></script>
	<script src="/Scripts/myajax.js" type="text/javascript"></script>
	<script src="/Scripts/Cookies.js" type="text/javascript"></script>
	<script src="/Service/Script.js?siteId=@BaseController.SelfSiteId" type="text/javascript"></script>
	
	<script src="/Scripts/jquery.zclip.js" type="text/javascript"></script>
	<script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php" type="text/javascript"></script>
	<script type="text/javascript">
		FB.init("@Skyner.Server.Extensions.Constants.FacebookApplicationKey", "Facebook"); 
	</script>
</head>
<body>
<div class="infoSite">
	<div class="verticalMenu">
		<ul>
			<li>@Url.Sites().AsLink("Viewing of your domains")</li>
			<li><br /></li>
			<li>@Url.ChangePassword().AsLink("Change password")</li>
			<li><br /></li>
			<li>@Url.AccountBinding().AsLink("Change your social binding")</li>
		</ul>
	</div>
	<div class="siteGrid">
	</div>
</div>
</body>